[package]
name = "create_doc_images"
version = "0.1.0"
edition = "2024"
description = "Creates documentation plots for the stem_material crate"
license  = "MIT OR Apache-2.0"
publish = false

[dependencies]
stem_material = { path = "../.."}
plotters = "0.3.3"